### ISSUE TITLE
Good utility to test ring buffer?

### ISSUE THREAD

**Issue by schveiguy** [eBay/tsv-utils-dlang#136]
I have added a new type of buffer to iopipe that allows me to avoid copying at all (even when the buffer needs to be reused). It works by using some mmap magic that @DmitryOlshansky clued me into at dconf.

However, I have discovered after getting it to work, that it's performance is pretty much equivalent to the original buffer type. The reason is that my "big test case" is byline, and byline copies very little data to begin with (and not very often). I wondered if you have any utilities that would benefit from such a buffer? Basically I'm looking for an example case that keeps a lot of data in the buffer at a time.

If you don't have any, I'm going to implement an example of keeping N lines in buffer at once (think of a grep-style iopipe that can be used to print N lines of context around the match). I think this should show some significant difference, but I wondered if you had examples that would be relevant in this library?

**Comment by schveiguy** [comment]
BTW, I haven't published the buffer type yet, just hammering out all the details right now.

**Comment by jondegenhardt** [comment]
`csv2tsv` uses File.byChunk reading a 1MB buffer at a time. Is this what you mean? 

The buffer gets copied to the output buffer scheme I created (based on Appender) before getting flushed to stdout. Any conversions necessary happen as part of writing the output buffer.

The `keep-header` tool also reads this same way. I don't have any standardized benchmarks for it, but they could be developed. It's been a while since I ran benchmarks against `keep-header`, but I remember it being a tick slower than some other approaches that operate using bash shells directly. I suspect because there was an extra copy of the data occurring.

**Comment by schveiguy** [comment]
No, what I mean is that you need enough data in the buffer to be able to go back and look at it. It would be more like you need to have 5 chunks (e.g. 200k) in memory at once at all times. As you read a chunk, you discard the oldest one, etc.

With byChunk, you are flushing *all* the data, and reading in a new chunk. So that's very similar to byLine, just bigger. This means you don't have to copy any data from the end of the buffer to the beginning of the buffer when you want to reuse it. What I'm looking for is a case where you need a lot of data in the buffer, so that you normally would have to copy this data, but with the ring buffer implementation, you don't have to copy any data, so it should outperform the normal buffer.

The good news at least is that it's not any *worse* than the normal buffer, but I'd love to have a real-world example to showcase why you would want to use it.

**Comment by schveiguy** [comment]
> e.g. Median of field 3. However, this doesn't fit your use-case.

Indeed, that needs to read *all* the data, not just a window.

> This does a look-ahead to decide what the field types and field lengths are

This is a temporary lookahead, and likely is only done once? I'm looking for an example that keeps the buffer usage high continuously. I think I will have to implement my grep copy to see how it performs.
