### ISSUE TITLE
keep-header missing dub.json

### ISSUE THREAD

**Issue by schveiguy** [eBay/tsv-utils-dlang#44]
When I run dub in tsv-utils to build, I get this:

```
Stevens-MacBook-Pro:tsv-utils-dlang steves$ dub
Unknown dependency: tsv-utils-dlang:keep-header
Stevens-MacBook-Pro:tsv-utils-dlang steves$ 
```

Looks like the dub.json file is missing in the keep-header directory. I can mock up one based on another dub.json, but the real description/etc I'd prefer you to make.

**Comment by jondegenhardt** [comment]
Thanks for the report. Should be fixed now. Already had the dub.json file, but forgot to add it to the repo.

**Comment by schveiguy** [comment]
Yep, fixes it, thanks.
