### ISSUE TITLE
Statically linked binaries for Linux

### ISSUE THREAD

**Issue by jacob-carlborg** [eBay/tsv-utils-dlang#67]
It would be nice if the pre-compiled binaries for Linux were statically linked. This would allow them to work on a more variety of Linux distributions and versions. Since it looks like there are no external dependencies it should be pretty simple when compiling with LDC to just add the `-static` flag.

**Comment by jondegenhardt** [comment]
Thank you for this tip. I will do this.

**Comment by jacob-carlborg** [comment]
BTW, DMD does not support static linking. It doesn't support the TLS model that is required, as far as I can see.

**Comment by jondegenhardt** [comment]
Thanks again for raising this topic. I was wondering how broadly these pre-built binaries would work. 

I'm trying the -static flag now. There's a bit to it. As you indicate, DMD does not support. And, LDC2 fails if it is used on OS X, so it's necessary to customize builds. Trying it on a Linux box, I'm getting a warning message indicating:
```
warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
I'm guessing this indicates there could still be issues. Do you thoughts on this? Also, can you list a specific linux distribution where the pre-built binaries I created won't work? I can try to get access to a box if I know what to try.

**Comment by jacob-carlborg** [comment]
macOS doesn't support static linking libc. But macOS doesn't have the same problem of binary compatibility as Linux does, only one distrubtion 😃. If you want to support older versions of you can use the environment variable `MACOSX_DEPLOYMENT_TARGET=<version>`, where `<version>` is the oldest version you want to support. D applications require 10.7 or later. I'm not sure if environment variables are supported in Dub. If the environment variable doesn't work you can use this Dub configuration:

```
"lflags-osx": ["-macosx_version_min", "10.7", "-lcrt1.o"]
```

An easy way to check if it properly reads the deployment target is to use version 10.6, which should give an error due to TLS is not supported.

As far as static linking on Linux. It's not possible to statically link 100% of glibc due to `gethostbyname` (as you noticed), but I'm pretty sure you don't need that. Assuming you need to get the hostname, it should work. To fully statically link libc you need another version than glibc, like musl or similar. Although D doesn't support musl right now. The runtime depends on a non-standard backtrace function that only exists in glibc. 

The pre-built binaries don't work on CentOS 6.

**Comment by jondegenhardt** [comment]
Okay, so what you are saying is that it should fine to ignore the warning messages about `gethostbyname` for Linux. Thanks for all this help. It'll probably be a day before I get back to this, but I'll post an update to this thread when I've got the binaries updated.

**Comment by jacob-carlborg** [comment]
> Okay, so what you are saying is that it should fine to ignore the warning messages about `gethostbyname` for Linux

Yes.

**Comment by jondegenhardt** [comment]
The pre-compiled binaries are now statically linked (version v1.1.10). If you get a chance to try them on CentOS 6 or other systems let me know if they work properly.

**Comment by jacob-carlborg** [comment]
Thanks. I'll give them a try.

**Comment by jacob-carlborg** [comment]
Works now. Thanks.
