### ISSUE TITLE
Column-wise 1:1 append

### ISSUE THREAD

**Issue by Wyatts** [eBay/tsv-utils-dlang#70]
Haha, while writing #68, I realised a couple other ones.  This time, I realised there's no easy way to simply append a column to a TSV, as far as I can tell.  Maybe something like this:
```
$ cat sample.tsv
foo	1	2
foo	3	22
foo	5	222
$ tsv-join --append sample.tsv sample.tsv
foo	1	2	foo	1	2
foo	3	22	foo	3	22
foo	5	222	foo	5	222
```
No filter file, just a line-by-line append.  This would be useful for the cases where I want to calculate some sort of derived column and append it to the original file at the end of my pipeline or a periodic addition of new aggregated data in a time-series.

**Comment by jondegenhardt** [comment]
Unix `paste` command has this functionality. Does it handle the cases you are looking for?

**Comment by Wyatts** [comment]
Yeah, I admit I completely forgot about paste.  This is probably not a very important one, then.
