### ISSUE TITLE
Print tool name with error message

### ISSUE THREAD

**Issue by Wyatts** [eBay/tsv-utils-dlang#85]
Hey there, been a while!  Just noticed that something I thought should work doesn't.  But at what point in the pipeline did things go wrong?  So I had to remove things one at a time until the bug unfurled.  I'd like it if error messages printed their name before the error.  e.g.
`[csv2tsv] Error: Not enough fields in line. File: Standard Input,  Line: 3`

**Comment by jondegenhardt** [comment]
Hi @Wyatts - I tried to have all the tools include the tool name in the error text as part of the 1.1.11 release. I did a quick scan through the code, I didn't find cases were the name was omitted, but I could have missed some. Can you give the command line you used and the exact error message produced? That will help track it down.

**Comment by Wyatts** [comment]
Ah, jeeze, I should have gotten some sleep before filing this.  Didn't realise that I was using old code because I ran git pull and didn't realise I was pointed at the wrong upstream.  Sorry about the noise. orz
RESOLVED INVALID
